"""initial migration

Revision ID: bcef4a0a80bd
Revises: 
Create Date: 2020-08-02 00:08:40.803902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcef4a0a80bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hacker Rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('e_num', sa.Text(), nullable=True),
    sa.Column('e_name', sa.Text(), nullable=True),
    sa.Column('hr_userid', sa.Text(), nullable=True),
    sa.Column('cert', sa.Text(), nullable=True),
    sa.Column('skill', sa.Text(), nullable=True),
    sa.Column('badges', sa.Text(), nullable=True),
    sa.Column('n_stars', sa.Integer(), nullable=True),
    sa.Column('c_p', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pragati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('em_num', sa.Text(), nullable=True),
    sa.Column('em_name', sa.Text(), nullable=True),
    sa.Column('no_sub', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shrishti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_pre', sa.Text(), nullable=True),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('e_num', sa.Text(), nullable=True),
    sa.Column('presenter', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shrishti')
    op.drop_table('pragati')
    op.drop_table('Hacker Rank')
    # ### end Alembic commands ###
