"""initial migration

Revision ID: c9006890c7b1
Revises: 
Create Date: 2020-08-11 00:03:32.138508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9006890c7b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_master',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_first_name', sa.Text(), nullable=True),
    sa.Column('employee_last_name', sa.Text(), nullable=True),
    sa.Column('employee_hacker_rank_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('project_master',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_start_date', sa.Text(), nullable=True),
    sa.Column('project_end_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_master.employee_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project_master.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_employee')
    op.drop_table('project_master')
    op.drop_table('employee_master')
    # ### end Alembic commands ###
